# Generated by Django 5.0.1 on 2024-01-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
