# Generated by Django 5.0.1 on 2024-01-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_genre_alter_product_category_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
    ]
